// Auto-generated by `supabase gen types typescript`. Do NOT hand-edit.
// Run: pnpm --filter @zeal/database gen-types
// Stub below keeps TypeScript happy until real types are generated.

export type Json =
  | string | number | boolean | null
  | { [key: string]: Json | undefined }
  | Json[];

type Role = "USER" | "CLIENT_ADMIN" | "SUPER_ADMIN" | "ADMIN" | "SUPPORT" | "VIEWER";
type ConsultantStatus = "PENDING" | "VERIFIED" | "REJECTED" | "SUSPENDED";
type ConsultantCategory =
  | "ASTROLOGER" | "PSYCHOLOGIST" | "TAROT" | "NUMEROLOGIST" | "PALMIST"
  | "VASTU" | "REIKI" | "LIFE_COACH" | "MOTIVATIONAL_SPEAKER"
  | "SPIRITUAL_GUIDE" | "YOGA_INSTRUCTOR" | "HEALER";
type Faith = "HINDU" | "ISLAM" | "CHRISTIAN" | "BUDDHIST" | "JEWISH" | "SIKH" | "OTHER";
type BookingStatus =
  | "PENDING" | "CONFIRMED" | "IN_PROGRESS" | "COMPLETED"
  | "CANCELLED" | "MISSED" | "DISPUTED";
type CallStatus = "INITIATED" | "CONNECTED" | "ENDED" | "RECORDING_READY";
type TransactionType =
  | "TOPUP" | "PAYMENT" | "REFUND" | "PAYOUT" | "FEE" | "COMMISSION";

type Table<Row, Insert = Partial<Row>, Update = Partial<Row>> = {
  Row: Row; Insert: Insert; Update: Update;
};

export interface Database {
  public: {
    Tables: {
      User: Table<{
        id: string; email: string; username: string; name: string | null;
        avatar: string | null; role: Role; sparks: number; isVerified: boolean;
        createdAt: string; updatedAt: string;
      }>;
      UserPreferences: Table<{
        id: string; userId: string; interests: string[]; goals: string[];
        favoriteConsultants: string[]; createdAt: string; updatedAt: string;
      }>;
      UserActivity: Table<{
        id: string; userId: string; consultantId: string | null;
        type: string; createdAt: string;
      }>;
      Wallet: Table<{
        id: string; userId: string; balance: number; escrow: number;
        pendingIn: number; pendingOut: number; blocked: number;
        createdAt: string; updatedAt: string;
      }>;
      Transaction: Table<{
        id: string; walletId: string; type: TransactionType; amount: number;
        balance: number; description: string; referenceId: string | null;
        metadata: Json | null; createdAt: string;
      }>;
      Consultant: Table<{
        id: string; userId: string; category: ConsultantCategory;
        specialties: string[]; languages: string[]; bio: string | null;
        perMinuteRate: number; isVerified: boolean; isActive: boolean;
        faith: Faith; rating: number; totalConsultations: number; earnings: number;
        availability: Json; status: ConsultantStatus;
        verificationDocs: Json | null; rejectionReason: string | null;
        approvedBy: string | null; approvedAt: string | null;
        subdomain: string | null; subdomainActive: boolean;
        whiteLabelEnabled: boolean; theme: Json | null;
        chatRate: number | null; audioRate: number | null;
        videoRate: number | null; physicalRate: number | null;
        bufferMinutes: number; createdAt: string; updatedAt: string;
      }>;
      AIConsultant: Table<{
        id: string; name: string; username: string; avatar: string;
        category: string; isPaid: boolean; perMinuteRate: number; rating: number;
        experience: number; totalConsultations: number; sparks: number;
        bio: string; specialties: string[]; languages: string[]; model: string;
        responseTime: number; accuracy: number; isActive: boolean;
        gender: string | null; persona: string | null; voiceStyle: string | null;
        isFeatured: boolean; createdAt: string; updatedAt: string;
      }>;
      Booking: Table<{
        id: string; userId: string | null; consultantId: string;
        scheduledAt: string; durationMinutes: number; status: BookingStatus;
        meetingLink: string | null; externalEmail: string | null;
        paymentId: string | null; amount: number; platformFee: number;
        consultantEarning: number; rating: number | null; review: string | null;
        createdAt: string; updatedAt: string;
      }>;
      CallSession: Table<{
        id: string; bookingId: string | null; userId: string;
        consultantId: string | null; isAI: boolean; aiConsultantId: string | null;
        startTime: string; endTime: string | null; durationSeconds: number;
        amount: number; status: CallStatus; recordingUrl: string | null;
        recordingReady: boolean; createdAt: string; updatedAt: string;
      }>;
      Post: Table<{
        id: string; content: string; mediaUrls: string[]; authorId: string;
        cheerCount: number; commentCount: number; shareCount: number;
        isPinned: boolean; isFlagged: boolean; createdAt: string; updatedAt: string;
      }>;
      Comment: Table<{
        id: string; content: string; authorId: string; postId: string;
        parentId: string | null; createdAt: string; updatedAt: string;
      }>;
      Cheer: Table<{ id: string; userId: string; postId: string; createdAt: string }>;
      Notification: Table<{
        id: string; userId: string; type: string; message: string;
        redirectUrl: string | null; read: boolean; actorId: string;
        createdAt: string; updatedAt: string;
      }>;
      Conversation: Table<{
        id: string; userAId: string; userBId: string; lastMessageAt: string;
        lastMessageText: string | null; createdAt: string; updatedAt: string;
      }>;
      ChatMessage: Table<{
        id: string; conversationId: string; senderId: string; content: string;
        readAt: string | null; createdAt: string;
      }>;
      AdminAuditLog: Table<{
        id: string; userId: string | null; email: string | null; action: string;
        targetType: string | null; targetId: string | null; metadata: Json | null;
        ip: string | null; userAgent: string | null; success: boolean; createdAt: string;
      }>;
      AdminInvite: Table<{
        id: string; email: string; role: Role; tokenHash: string;
        invitedBy: string; expiresAt: string; acceptedAt: string | null;
        revokedAt: string | null; createdAt: string;
      }>;
      AdminLoginAttempt: Table<{
        id: string; email: string; ip: string | null; success: boolean;
        reason: string | null; createdAt: string;
      }>;
      DebugLog: Table<{
        id: string; createdAt: string; level: string; channel: string;
        event: string; message: string | null; data: Json | null;
        durationMs: number | null; requestId: string | null;
        userId: string | null; route: string | null;
      }>;
    };
    Views: Record<string, never>;
    Functions: {
      toggle_cheer: { Args: { p_user_id: string; p_post_id: string }; Returns: Json };
      increment_comment_count: { Args: { p_post_id: string }; Returns: number };
      claim_quest: { Args: { p_user_id: string; p_quest_id: string; p_reward: number }; Returns: Json };
      cancel_booking: { Args: { p_booking_id: string; p_actor_id: string }; Returns: Json };
      end_call_session: { Args: { p_session_id: string }; Returns: Json };
      request_withdrawal: { Args: { p_user_id: string; p_amount: number; p_upi: string; p_bank: string }; Returns: Json };
      process_withdrawal: { Args: { p_tx_id: string; p_action: string; p_reason?: string | null }; Returns: Json };
      verify_consultant: { Args: { p_consultant_id: string; p_admin_id: string; p_action: string; p_reason?: string | null; p_subdomain?: string | null }; Returns: Json };
      check_booking_conflict: { Args: { p_consultant_id: string; p_start: string; p_duration_minutes: number }; Returns: boolean };
      ledger_debit: { Args: { p_wallet_id: string; p_amount: number; p_type: TransactionType; p_description: string; p_reference_id: string | null; p_metadata?: Json }; Returns: Json };
      ledger_credit: { Args: { p_wallet_id: string; p_amount: number; p_type: TransactionType; p_description: string; p_reference_id: string | null; p_metadata?: Json }; Returns: Json };
      ledger_transfer: { Args: { p_from_wallet: string; p_to_wallet: string; p_amount: number; p_reference_id: string; p_description: string }; Returns: Json };
    };
    Enums: {
      Role: Role;
      ConsultantStatus: ConsultantStatus;
      ConsultantCategory: ConsultantCategory;
      Faith: Faith;
      BookingStatus: BookingStatus;
      CallStatus: CallStatus;
      TransactionType: TransactionType;
    };
  };
}
